# ==========================================
# Janani Jobs - Application Security Config
# ==========================================
# Ensure this secret is at least 32 characters (256-bit) long for HS256 signature compliance
app.security.jwt.secret=your-super-long-secure-and-secret-key-that-is-at-least-256-bits-long!!
app.security.jwt.access-expiration-ms=900000
spring.application.name=backend

# ==========================
# PostgreSQL
# ==========================
spring.datasource.url=jdbc:postgresql://localhost:5432/jananijobs
spring.datasource.username=postgres
spring.datasource.password=Ravitheja6300@#
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG

# ==========================
# JPA
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# Flyway
# ==========================
spring.flyway.enabled=true

# ==========================
# Server
# ==========================
server.port=8080